// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMDiidfd1EyY0443v7jFYhV9ti4dWRkM4',
    appId: '1:331796268559:web:dd7b75a2e108813765857a',
    messagingSenderId: '331796268559',
    projectId: 'eazymart-87519',
    authDomain: 'eazymart-87519.firebaseapp.com',
    storageBucket: 'eazymart-87519.appspot.com',
    measurementId: 'G-8RLEKR3H5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB55J8fwN48VHbSB1v2IQQU2U5v_ESGhis',
    appId: '1:331796268559:android:dbd267cd7bdcc42c65857a',
    messagingSenderId: '331796268559',
    projectId: 'eazymart-87519',
    storageBucket: 'eazymart-87519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-uc3TP9a_2lsAKBv7fnaowVQ_Td4Bk8',
    appId: '1:331796268559:ios:f818b4232cf766f865857a',
    messagingSenderId: '331796268559',
    projectId: 'eazymart-87519',
    storageBucket: 'eazymart-87519.appspot.com',
    iosClientId: '331796268559-e16hfds1h6jsg2if8adjroj4p8s5bh73.apps.googleusercontent.com',
    iosBundleId: 'com.example.easymartShreejan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR-uc3TP9a_2lsAKBv7fnaowVQ_Td4Bk8',
    appId: '1:331796268559:ios:cb8ca1a55a37393b65857a',
    messagingSenderId: '331796268559',
    projectId: 'eazymart-87519',
    storageBucket: 'eazymart-87519.appspot.com',
    iosClientId: '331796268559-2rnqoq20cqqfsoj4no74ae4ijccqkmhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.easymartShreejan.RunnerTests',
  );
}
